# Generated by Django 4.1.7 on 2023-03-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
