# Generated by Django 4.1.7 on 2023-03-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_auto_20230312_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tests_taken",
            field=models.IntegerField(
                default=0, verbose_name="количество пройденых тестов"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="coins",
            field=models.IntegerField(default=0, verbose_name="количество монет"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="scores",
            field=models.IntegerField(default=0, verbose_name="количество очков"),
        ),
    ]
