# Generated by Django 4.1.7 on 2023-03-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_background_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="background_color",
            field=models.CharField(
                choices=[
                    ("background-color:#f2100c", "Красный"),
                    ("background-color:#0000FF", "Синий"),
                    ("background-color:#FFA500", "Оранжевый"),
                    ("background-color:#008000", "Зеленый"),
                    ("background-color:#800080", "Фиолетовый"),
                    ("background-color:#ccc01f", "Золотой"),
                ],
                default="background-color:#008000",
                max_length=24,
                verbose_name="код цвета логина",
            ),
        ),
    ]
